### ISSUE TITLE
Wierd Bugs

### ISSUE THREAD

**Issue by PalgamingHD** [Draylar/into-the-omega#1]
all boots have frost walker, all items have fire aspect (And Knockback), maybe some others that I haven't seen yet

**Comment by PalgamingHD** [comment]
Found another one: You always have respiration(helmet or not) idk which level though

**Comment by Draylar** [comment]
Yeah, got a report on this earlier, no idea how I missed it... looking into it

**Comment by Draylar** [comment]
Fixed in 1.0.1 beta, thanks for the report!
