### ISSUE TITLE
Any way of telling what the equivalent non-Omega level of a given Ω-enchantment is?

### ISSUE THREAD

**Issue by James103** [Draylar/into-the-omega#13]
Currently, there appears to be no way to tell what the equivalent non-Omega enchantment level for a given Ω-enchantment without knowing the max level of said enchantment. If only there is a way to make it so if you held some modifier key such as Ctrl, that it will show the enchantments as for example: "Protection VI (Ω: II)" instead of "Ω Protection II", or "Efficiency X (Ω: V)" instead of "Ω Efficiency V" or something similar. In other words, it will show the equivalent level of the non-Omega version of the enchantment in addition to the Ω level of the enchantment for any Ω-enchantments on the item.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/91349485-f8a15280-e7aa-11ea-98d7-1acbf4eed5bf.png)
Implemented in the next version (press control to show), good idea!
