### ISSUE TITLE
Instance Won't Launch

### ISSUE THREAD

**Issue by Areorah** [Draylar/into-the-omega#15]
Version: 1.1.1-beta
MC Version: 1.16.2
Fabric Version: 0.9.6 Build:206

I am using GDL and whenever I launch with this mod as well as my other mods, it won't launch. If I disable this mod, it will launch. I'm new to Fabric and I know this isn't a crashlog, because one isn't generating.

https://hastebin.com/ucunokoxib.cpp

**Comment by Draylar** [comment]
LOL, [End Rebellion is literally nuking the entire method for adding features to the end](https://github.com/EleC0TroN/ER/blob/b1969831a8dd2131d29f726fd4729ef1f8fb540f/src/main/java/net/electron/endreborn/mixin/TheEndBiomeMixin.java#L21). Not sure what their goal was there... maybe they ran out of time and had to do it quickly? hahahaha

For reference, [I add through an inject](https://github.com/Draylar/into-the-omega/blob/eaf40cd1c2f906413c0f225a99fc1f0d6de3bdba/src/main/java/draylar/intotheomega/mixin/DefaultBiomeCreatorMixin.java#L19), which should cause 0 compatibility issues.

**Comment by Areorah** [comment]
Alright, I'll go post something on their end.
