### ISSUE TITLE
Game crashing on start

### ISSUE THREAD

**Issue by ghost** [Draylar/into-the-omega#24]
I want to test this mod on 1.18.2, but my game doesn't even start, it's crashing and i'm just using the last version of fabric api, geckolib, trinkets and your mod.

Here is my log.
[latest.log](https://github.com/Draylar/into-the-omega/files/8781186/latest.log)

**Comment by Draylar** [comment]
Hi Dark, thanks for the report. I recently uploaded a new [1.2.2 alpha version](https://www.curseforge.com/minecraft/mc-mods/into-the-omega/files/3806510) which should fix this problem. Give it a try and let me know if you can get in okay!
