### ISSUE TITLE
crashing on start 1.18.2

### ISSUE THREAD

**Issue by Ajw2003** [Draylar/into-the-omega#25]
attached is my log

I simply let curse forge install the mod and the correct dependencies and even trying the fabric loader version listed in the manifest as well as the latest version the mod simply crashes

[2022-05-26-2.log](https://github.com/Draylar/into-the-omega/files/8782478/2022-05-26-2.log)

**Comment by Draylar** [comment]
Thank you for the report - the file at https://www.curseforge.com/minecraft/mc-mods/into-the-omega/files/3806510 (new version - 1.2.2 alpha for 1.18.2) should fix this problem. Please give it a try and let me know how it goes!
